"""initial

Revision ID: ca7a0ac27660
Revises: 
Create Date: 2026-06-03 19:47:10.751476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = 'ca7a0ac27660'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('crunchbase_url', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('funding_total', sa.Integer(), nullable=True),
    sa.Column('last_funding_date', sa.Date(), nullable=True),
    sa.Column('investor_list', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('relevance_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('strategic_notes', sa.Text(), nullable=True),
    sa.Column('company_summary', sa.Text(), nullable=True),
    sa.Column('recent_news', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conferences',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('goals', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('target_contact_types', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('schedule_imported', sa.Boolean(), nullable=False),
    sa.Column('summary_generated', sa.Boolean(), nullable=False),
    sa.Column('post_conference_report', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_user_id'), 'conversation_messages', ['user_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('meeting_type', sa.Enum('pitch', 'intro', 'casual', 'panel', 'coffee', 'scheduled', 'spontaneous', name='meetingtype'), nullable=False),
    sa.Column('conference_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('prep_brief', sa.Text(), nullable=True),
    sa.Column('talking_points', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('questions_to_ask', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('outcome_summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Enum('very_positive', 'positive', 'neutral', 'negative', name='sentiment'), nullable=True),
    sa.Column('next_steps', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('followed_up', sa.Boolean(), nullable=False),
    sa.Column('followed_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('twitter_handle', sa.String(), nullable=True),
    sa.Column('contact_type', sa.Enum('investor', 'customer', 'partner', 'founder', 'speaker', 'other', name='contacttype'), nullable=False),
    sa.Column('priority_tier', sa.Enum('A', 'B', 'C', 'unranked', name='prioritytier'), nullable=False),
    sa.Column('interest_level', sa.Enum('hot', 'warm', 'cold', 'unknown', name='interestlevel'), nullable=False),
    sa.Column('warmth_score', sa.Float(), nullable=False),
    sa.Column('how_met', sa.String(), nullable=True),
    sa.Column('first_interaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_interaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_status', sa.Enum('pending', 'in_progress', 'completed', 'not_needed', name='followupstatus'), nullable=False),
    sa.Column('next_action', sa.String(), nullable=True),
    sa.Column('next_action_due', sa.Date(), nullable=True),
    sa.Column('linkedin_summary', sa.Text(), nullable=True),
    sa.Column('bio_snapshot', sa.Text(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrichment_source', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkedin_url')
    )
    op.create_table('interactions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('person_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('meeting_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('interaction_type', sa.Enum('conversation', 'pitch', 'email', 'linkedin_message', 'introduction', 'follow_up', name='interactiontype'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_note', sa.Text(), nullable=True),
    sa.Column('processed_summary', sa.Text(), nullable=True),
    sa.Column('topics_discussed', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('commitments_made', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment', sa.Enum('very_positive', 'positive', 'neutral', 'negative', name='sentiment'), nullable=True),
    sa.Column('source', sa.Enum('voice', 'text', name='notesource'), nullable=False),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('person_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('meeting_id', 'person_id')
    )
    op.create_table('notes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('person_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('meeting_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('voice', 'text', name='notesource'), nullable=False),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('opportunity_type', sa.Enum('investment', 'customer', 'partnership', 'co_founder', 'advisor', 'press', name='opportunitytype'), nullable=False),
    sa.Column('person_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('stage', sa.Enum('identified', 'contacted', 'interested', 'proposal_sent', 'negotiating', 'closed_won', 'closed_lost', 'nurture', name='opportunitystage'), nullable=False),
    sa.Column('estimated_value', sa.String(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pitch_feedback', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('objections_raised', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('next_step', sa.String(), nullable=True),
    sa.Column('next_step_due', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('send_email', 'send_deck', 'schedule_meeting', 'linkedin_connect', 'research', 'follow_up', 'other', name='tasktype'), nullable=False),
    sa.Column('related_person_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('related_company_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('related_meeting_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('note_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('priority', sa.Enum('urgent', 'high', 'medium', 'low', name='taskpriority'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='taskstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('draft_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['related_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['related_meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['related_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute('DROP EXTENSION IF EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('opportunities')
    op.drop_table('notes')
    op.drop_table('meeting_participants')
    op.drop_table('interactions')
    op.drop_table('people')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_conversation_messages_user_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_table('conferences')
    op.drop_table('companies')
    # ### end Alembic commands ###
